entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy-network

certificatesResolvers:
  myresolver:
    acme:
      email: darkgabu123@gmail.com
      storage: "acme.json"
      httpChallenge:
        entryPoint: web
